# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UniBookApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UniBookApp
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  target 'UniBookAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UniBookAppUITests' do
    # Pods for testing
  end

end
